# Generated by Django 4.2.16 on 2024-11-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0003_auto_20241122_2001"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                null=True,
            ),
        ),
    ]
