# Generated by Django 4.2.16 on 2024-12-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gaming",
            "0007_image_statusmessage_remove_profile_profile_image_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(upload_to="profile_images/"),
        ),
    ]
