# Generated by Django 4.2.16 on 2024-12-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0008_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="platform",
            field=models.CharField(
                choices=[
                    ("PC", "PC"),
                    ("PlayStation", "PlayStation"),
                    ("Xbox", "Xbox"),
                    ("Nintendo", "Nintendo"),
                ],
                max_length=100,
            ),
        ),
    ]
