# Generated by Django 4.2.16 on 2024-12-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0010_platform_remove_game_platform_game_platforms"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="platform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="gaming.platform",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progress",
            name="completion_status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                    ("Wishlist", "Wishlist"),
                ],
                default="Not Started",
                max_length=20,
            ),
        ),
    ]
