# Generated by Django 4.2.16 on 2024-12-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0011_progress_platform_alter_progress_completion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="platform",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="gaming.platform",
            ),
        ),
    ]
