# Generated by Django 4.2.16 on 2024-12-10 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0012_alter_progress_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="gaming.platform",
            ),
        ),
    ]
