# Generated by Django 4.2.16 on 2024-12-10 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("gaming", "0016_progress_timestamp_feeditem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="like", unique_together=set(),),
        migrations.RemoveField(model_name="comment", name="content",),
        migrations.RemoveField(model_name="comment", name="status_message",),
        migrations.AddField(
            model_name="comment",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="like", unique_together={("profile", "content_type", "object_id")},
        ),
        migrations.RemoveField(model_name="like", name="status_message",),
    ]
